// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: Battleground Warfare
 *------------------------------------------*/
		ACMD_FUNC(reloadbg);
		ACMD_FUNC(bgregister);
		ACMD_FUNC(bgjoin);
		ACMD_FUNC(bgunregister);
		ACMD_FUNC(bgleave);
		ACMD_FUNC(bgranking);
		ACMD_FUNC(bgwaiting);
		ACMD_FUNC(bgplaying);
		ACMD_FUNC(bgreportafk);
		//ACMD_FUNC(bgorder);
		ACMD_FUNC(bgchangeleader);
		ACMD_FUNC(bgreloadrewards);
