// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: Battleground Warfare
 *------------------------------------------*/
BUILDIN_FUNC(bg_create_team);
BUILDIN_FUNC(bg_join_team);
BUILDIN_FUNC(bg_kick_team);
BUILDIN_FUNC(bg_team_search);
BUILDIN_FUNC(bg_team_size);
BUILDIN_FUNC(bg_get_team);
BUILDIN_FUNC(bg_set_respawn);
BUILDIN_FUNC(bg_attach_respawn);
BUILDIN_FUNC(bg_attach_respawn_all);
BUILDIN_FUNC(bg_viewpoint);
BUILDIN_FUNC(bg_team_getxy);
BUILDIN_FUNC(bg_respawn_getxy);
BUILDIN_FUNC(bg_areapercentheal);
BUILDIN_FUNC(bg_refresh_patent);
BUILDIN_FUNC(bg_message);
BUILDIN_FUNC(bg_digit_timer);
BUILDIN_FUNC(bg_reward);
BUILDIN_FUNC(bg_get_score);
BUILDIN_FUNC(bg_set_score);
BUILDIN_FUNC(bg_set_npc);
BUILDIN_FUNC(bg_npc_getid);
BUILDIN_FUNC(bg_flag_click);
BUILDIN_FUNC(bg_flag_respawn);
BUILDIN_FUNC(bg_console);
