// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: Queue System
 *------------------------------------------*/
ACMD_FUNC(queue);
ACMD_FUNC(queuelist);
ACMD_FUNC(queuekick);
ACMD_FUNC(queuesetdelay);
ACMD_FUNC(queuedelay);
ACMD_FUNC(queuenomove);