// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: Queue System
 *------------------------------------------*/
BUILDIN_FUNC(queue_create);
BUILDIN_FUNC(queue_delete);
BUILDIN_FUNC(queue_check);
BUILDIN_FUNC(queue_size);
BUILDIN_FUNC(queue_join);
BUILDIN_FUNC(queue_leave);
BUILDIN_FUNC(queue_clean);
BUILDIN_FUNC(queue_leave_notify);
BUILDIN_FUNC(queue_get_players);
BUILDIN_FUNC(queue_get_data);
BUILDIN_FUNC(queue_set_data);
BUILDIN_FUNC(queue_char_info);
BUILDIN_FUNC(queue_set_delay);
