// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos
//

 /*==========================================
  * CreativeSD: Stuff Items
  *	 getstuffitem <item id>, <amount>, <type>;
  *  getstuffitem <"item name">, <amount>, <type>;
  *------------------------------------------*/
BUILDIN_FUNC(getstuffitem);