// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos
//

// * getmapxyunit <GID>, .@var$, .@x, .@y;
BUILDIN_FUNC(getmapxyunit);
// * alive {"<player_name>"};
BUILDIN_FUNC(alive);
// * countguild(<guild_id>);
BUILDIN_FUNC(countguildmap);
// * getcharisdead(<name>)
BUILDIN_FUNC(getcharisdead);
// * getplayersarea "<map>", "<x1>", "<y1>", "<x2>", "<y2>";
BUILDIN_FUNC(getplayersarea);
// * getplayersrange "<map>", "<x1>", "range";
BUILDIN_FUNC(getplayersrange);
// * setlangtype <lang_num>{, "<player>"};
BUILDIN_FUNC(setlangtype);