// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

	/*==========================================
	 * CreativeSD: Ranked System
	 *------------------------------------------*/
		ACMD_DEF(reloadrankdb),
		ACMD_DEF(rankinfo),
		ACMD_DEF(rankinfo2),
		ACMD_DEF(rankinfo3),
		ACMD_DEF(rankshow),
		ACMD_DEF(ranklist),
		ACMD_DEF(setrank),
		ACMD_DEF(setrankpoints),