// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: Ranked System
 *------------------------------------------*/
ACMD_FUNC(reloadrankdb);
ACMD_FUNC(rankinfo);
ACMD_FUNC(rankinfo2);
ACMD_FUNC(rankinfo3);
ACMD_FUNC(rankshow);
ACMD_FUNC(ranklist);
ACMD_FUNC(setrank);
ACMD_FUNC(setrankpoints);
