// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos

/*==========================================
 * CreativeSD: Ranked System
 *------------------------------------------*/
	BUILDIN_DEF(getrankinfo, "ii"),
	BUILDIN_DEF(getcharrankinfo, "i?"),
	BUILDIN_DEF(setrankpoints, "v??"),
	BUILDIN_DEF(setrank, "i??"),