// © Creative Services and Development
// Site Oficial: www.creativesd.com.br
// Termos de Contrato e Autoria em: http://creativesd.com.br/?p=termos
//

/// bindclock "<hour>:<minute>", "<npc_event::label>";
BUILDIN_FUNC(bindclock);
/// unbindclock "<hour>:<minute>", "<npc_event::label>";
BUILDIN_FUNC(unbindclock);
/// checkbindclock("<hour:minute>", "<npc_event::label>");
BUILDIN_FUNC(checkbindclock);